name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar do Docker Hub
        run: echo "Executando o comando Docker login"
      - name: Construção da imagem Docker
        run: echo "Executando comando DOcker build"
      - name: Envio da imagem Docker
        run: echo "Executando comando Docker push"
